### ISSUE TITLE
Thread 'main' panicked at 'static values are valid

### ISSUE THREAD

**Issue by eniken777** [Cell-chain/wiki#15]
PS C:\Cell.io> .\cell-win.exe --miner 5FPLsMvsy6z71B9NXos1KcfXPU9U5BXUyrGBGbHEs1Ngdfr4
←[2m2022-02-07 14:20:31←[0m Cell Node
←[2m2022-02-07 14:20:31←[0m ✌️  version 0.4.0-f8889ab-x86_64-windows-msvc
←[2m2022-02-07 14:20:31←[0m ❤️  by Celllab <https://github.com/cell-chain>, 2021-2022
←[2m2022-02-07 14:20:31←[0m 📋 Chain specification: Cell Testnet
←[2m2022-02-07 14:20:31←[0m 🏷 Node name: cooing-regret-1018
←[2m2022-02-07 14:20:31←[0m 👤 Role: FULL
←[2m2022-02-07 14:20:31←[0m 💾 Database: RocksDb at C:\Users\owner\AppData\Local\cell-win.exe\data\chains\cell_testnet\db
←[2m2022-02-07 14:20:31←[0m ⛓  Native runtime: cell_testnet-101 (cell_testnet-1.tx1.au1)
←[2m2022-02-07 14:20:32←[0m 🏷 Local node identity is: 12D3KooWFNyuvVqe9gdGenD9XWaNG65i8TPSgVLwqJcZt 
←[2m2022-02-07 14:20:32←[0m 📦 Highest known block at #0
←[2m2022-02-07 14:20:32←[0m Multi-threaded server is not available on Windows. Falling back to single thread.
←[2m2022-02-07 14:20:32←[0m 〽️ Prometheus server started at 127.0.0.1:9615
←[2m2022-02-07 14:20:32←[0m Listening for new connections on 127.0.0.1:9944.

====================

Version: 0.4.0-f8889ab-x86_64-windows-msvc

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: BaseThreadInitThunk
  22: RtlUserThreadStart

Thread 'main' panicked at 'static values are valid; qed: InvalidPhrase', E:\code\chain\carbon\node\miner\src\lib.rs:227

This is a bug. Please report it at:

        https://github.com/Cell-chain/wiki.git

**Comment by Cell-chain** [comment]
Your miner's key is invalid.
the sample: 0xd606b3d846eb749fa440365103a5d10a33e099fb7d4adae8091f251d13e15f8e

**Comment by eniken777** [comment]
thanks

**Comment by eniken777** [comment]
> Your miner's key is invalid. the sample: 0xd606b3d846eb749fa440365103a5d10a33e099fb7d4adae8091f251d13e15f8e
