### ISSUE TITLE
I can't start it

### ISSUE THREAD

**Issue by 1923998238** [Cell-chain/wiki#3]
![image](https://user-images.githubusercontent.com/64238420/150661508-3d6fb71e-d700-424a-a814-89137898c6a4.png)

I need help
I can't start it

My system is windows 10

**Comment by Cell-chain** [comment]
What command did you type in?

**Comment by 1923998238** [comment]
`.\cell-win.exe --base-path E:\CELL --miner 0x****************************************************************`
![image](https://user-images.githubusercontent.com/64238420/150675702-4708f4f8-c40a-406e-97fd-5a07946641bb.png)

**Comment by Cell-chain** [comment]
You can run `Get-FileHash .\params.bin -Algorithm SHA256 | Format-List` and `Get-FileHash .\witness.bin -Algorithm SHA256 | Format-List`  to check file hash.

the params.bin:
```
Algorithm : SHA256
Hash      : ECD8A4E553F6A676AB36139F6597923E4D19DCE12B3CC0BCB8BB95F60AD36727
```

the witness.bin:
```
Algorithm : SHA256
Hash      : 03329749D79BB05368C93FD2823385D3D8E08B17B7EE5281A6515D2B203A4F37
```

maybe there's a file error.

**Comment by 1923998238** [comment]
Thank you, I didn't update this file when I update the program, causing this error, now there is no problem.
