### ISSUE TITLE
Problem with port and localhost port when using Multiple Nodes on SingleMachine

### ISSUE THREAD

**Issue by trungdeveloper199** [Cell-chain/wiki#6]
I am trying to run multiple node on single machine.
- first node is working well and like the picture: 
![ảnh](https://user-images.githubusercontent.com/15366439/150737263-aac503fa-2d5e-479b-8fb4-8fbf32483401.png)
- Second node is not working when i only use command:
./cell --base-path=/mnt/node2 --miner <key>
![ảnh](https://user-images.githubusercontent.com/15366439/150737437-46008959-c4b2-4305-8232-2be8fde9888f.png)
Port already in use. and best block always: 107536. Not current block on Cell

- Change port with command: 
./cell --port=30335 --base-path=/mnt/node2 --miner <key>
![ảnh](https://user-images.githubusercontent.com/15366439/150738059-25cb22f0-f02b-4c2f-9d6f-ed584e33d3c9.png)
new port is passed. But localport still has issue. and Best block always 107536. not current block on Cell

How to fix it?

**Comment by Cell-chain** [comment]
Hi. the node2 is run on old data, You can delete the data first with`cell purge-chain --base-path=/mnt/node2 -y`  or  `rm -r /mnt/node2/chains`

**Comment by trungdeveloper199** [comment]
That work! Thank so much
