### ISSUE TITLE
Miner ss58 account does not correspond to account ss58

### ISSUE THREAD

**Issue by vdmklchv** [Cell-chain/wiki#7]
Miner ss58 when the mining starts with account number is different to account ss58 number. I'm not sure it is an issue, just checking if it is designed to be so.

**Comment by Cell-chain** [comment]
May I ask what version of your cell is it?

How was your account created?

**Comment by vdmklchv** [comment]
I have followed the instructions on github and created account using cli with ./cell key generate . I've written down ss58 number, private keys and seed phrase.
My cell version is latest - version 0.4.0-f8889ab 
I run node with ./cell --miner my-acc-num    In logs I see the string where it shows miner ss58 acc number. It doesn't correspond to ss58 number of created account. Probably they shouldn't, but I'd like to confirm

**Comment by vdmklchv** [comment]
I will close the ticket. The wiki doesn't say one should provide secret seed and I fed it my acc number instead. I have restarted with secret seed and it shows correct ss58 number now. Definitely not a bug but a chance to update WIKI.

**Comment by Cell-chain** [comment]
I restarted the operation, but my account shows the same. It is certain that the Seed is passed in instead of the PublicKey

**Comment by vdmklchv** [comment]
It shows incorrect ss58 data (not mine) when using PublicKey. I used Seed instead and now it shows correct ss58 data
